### ISSUE TITLE
implement the encoder library

### ISSUE THREAD

**Issue by yashpatel1392** [perSEVERE-5962/rc_car_project#5]
**Tasks**
- [ ] import all required libraries, such as gpiozero, DigitalInputDevice, ...
- [ ] define the counter class - increments the encoder ticks
- [ ] implement PID
- [ ] implement the Initialize() method
- [ ] implement the GetValue() method
- [ ] implement the Reset() method
- [ ] allow to be imported and used by the main project
