### ISSUE TITLE
create network table class

### ISSUE THREAD

**Issue by david-lemasurier** [perSEVERE-5962/rc_car_project#7]
**Tasks**
- [ ] define the network table structure for commands
- [ ] create a class
     - [ ] start network table server
     - [ ] read function
     - [ ] write function
- [ ] update templates to use this class
